language: ruby
sudo: false
cache: bundler
script: bundle exec rake ci
bundler_args: --without=development

branches:
  only:
    - master

rvm:
  - 2.2.6
  - 2.3.3
  - jruby-9.1.6.0

matrix:
  fast_finish: true
  allow_failures:
    - env: CELLULOID_BACKPORTED=true
    - env: CELLULOID_BACKPORTED=false CELLULOID_LEAKTEST=1
    - env: CELLULOID_BACKPORTED=false CELLULOID_TASK_CLASS=Threaded
    - env: CELLULOID_BACKPORTED=true CELLULOID_TASK_CLASS=Threaded

env:
  global:
    - NUMBER_OF_PROCESSORS=4 CELLULOID_CONFIG_FILE=.env-ci
  matrix:
    - CELLULOID_BACKPORTED=true
    - CELLULOID_BACKPORTED=false
    - CELLULOID_BACKPORTED=false CELLULOID_LEAKTEST=1
    - CELLULOID_BACKPORTED=false CELLULOID_TASK_CLASS=Threaded
    - CELLULOID_BACKPORTED=true CELLULOID_TASK_CLASS=Threaded

notifications:
  irc: "irc.freenode.org#celluloid"
